[package]
name = "lang_study"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
antlr-rust = {git = "https://github.com/buguOS/antlr4rust"}